services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    ports:
#      - 5432:5432

  server:
    container_name: server
    build: .
    ports:
      - 8080:8080