version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
#    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    ports:
#      - 5432:5432

  server:
    container_name: server
    build: .
#    restart: always
#    environment:
#      DB_PORT: "5432"
#      DB_NAME: "${DB_NAME:-postgres}"
#      DB_USER: "${DB_USER:-postgres}"
#      DB_PASSWORD: "${DB_PASSWORD:-postgres}"
#    ports:
#      - 8080:8080